# Analisando as *features* selecionadas

In [25]:
import pandas as pd
import numpy as np

scenario01 = pd.read_csv('https://github.com/caiops/IA368X/raw/main/p2/data/interim/features/features_observations_01.csv')
scenario02 = pd.read_csv('https://github.com/caiops/IA368X/raw/main/p2/data/interim/features/features_observations_02.csv')

display(scenario01)
display(scenario02)

,PATIENT,BIRTHDATE,RACE,ETHNICITY,GENDER,DEATH_FN,AGE_FN_YEARS,BACTEREMIA,WELLNESS_CONT,AMBULATORY_SYMPTOM_CONT,MED_AMLD,NEUT_CONT,BODY_TEMP_F
0,4288f90b-4774-c329-3176-c1482e824c04,2010-07-13,white,nonhispanic,M,0,2,0,1.0,0.0,0,255.1,101.2
1,f03f50be-20b1-3eae-2ed1-bb478bceb320,2002-07-12,white,nonhispanic,M,0,16,1,6.0,1.0,1,491.4,102.2
2,11089781-c268-6838-642e-2c2c9edbb694,2011-07-17,white,nonhispanic,F,0,9,0,12.0,2.0,0,258.9,102.0
3,d7b9725d-889f-d178-cf41-dbf8b373eda9,2010-10-18,black,nonhispanic,F,0,6,0,7.0,1.0,0,360.7,102.9
4,ed2bb6aa-1f3c-b72b-46a6-54f05cac7da7,2008-04-09,asian,nonhispanic,M,0,12,0,7.0,2.0,0,364.6,100.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...
134,7d87bdff-2df1-8162-80e4-2e406304515d,2011-06-17,white,nonhispanic,M,0,2,0,4.0,0.0,0,479.1,101.0
135,d5c0cc48-5f8a-4533-325c-25a9c3284185,2017-10-05,other,nonhispanic,F,0,3,1,11.0,1.0,1,476.6,101.6
136,a4cabcbc-8282-5599-6b69-01e28e69c045,2004-09-24,black,nonhispanic,M,0,16,0,8.0,0.0,0,364.4,101.5
137,eca28495-500f-ab7e-356b-176f31382569,2017-03-03,white,nonhispanic,F,0,3,0,11.0,0.0,0,425.7,100.8
138,c815ffa4-2917-2c09-1569-e90d5a89eeb2,1933-05-23,white,nonhispanic,M,1,15,0,9.0,7.0,0,340.5,100.6

,PATIENT,BIRTHDATE,RACE,ETHNICITY,GENDER,DEATH_FN,AGE_FN_YEARS,BACTEREMIA,WELLNESS_CONT,AMBULATORY_SYMPTOM_CONT,MED_AMLD,NEUT_CONT,BODY_TEMP_F
0,bb37561b-ba65-7c47-db5b-0641bca883b4,2012-02-08,white,nonhispanic,M,0,3,0,9.0,1.0,0,406.5,102.3
1,678fc07c-1cb1-acc6-3553-d848200626e9,2006-02-11,white,nonhispanic,F,0,16,0,9.0,2.0,0,265.8,101.9
2,04efa71e-b8ed-980b-94a1-cd25e94b6015,2018-04-17,other,nonhispanic,F,0,4,0,13.0,2.0,0,496.3,101.7
3,1e466cbc-5018-4c1a-b132-cf8a4a4d87cf,1997-02-18,white,nonhispanic,F,0,21,1,4.0,10.0,0,321.7,101.8
4,8e9d1dd0-085f-a629-3ea6-9033f330b383,1996-03-07,white,nonhispanic,F,0,20,1,3.0,1.0,0,460.9,103.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
112,84c9e441-fa88-33c8-5d87-91b863998d26,1944-08-04,white,nonhispanic,F,1,2,1,9.0,1.0,0,250.6,100.9
113,7837ca92-1dc3-b3ef-a7f9-4207e439775c,1996-01-13,white,nonhispanic,M,0,17,0,15.0,2.0,0,435.9,101.1
114,3f3ad6c2-337b-9d48-47b7-b2197a0a0500,1969-07-18,white,nonhispanic,F,1,2,1,9.0,0.0,1,448.6,100.8
115,32d8410a-cc4b-4d8b-601d-3ad2b8ef912b,2006-08-23,white,nonhispanic,M,0,9,0,8.0,4.0,0,391.1,102.0
116,2e3402a9-45ff-3558-8450-375f17107ca0,2016-06-25,white,nonhispanic,M,0,5,1,14.0,2.0,0,303.6,100.8

## Morte dos pacientes

In [26]:
print('Porcentagem de pacientes que morreram (cenário 01):')
print(scenario01['DEATH_FN'].value_counts()[1]/len(scenario01['DEATH_FN']))
print('Porcentagem de pacientes que morreram (cenário 02):')
print(scenario02['DEATH_FN'].value_counts()[1]/len(scenario02['DEATH_FN']))

Porcentagem de pacientes que morreram (cenário 01):
0.18705035971223022
Porcentagem de pacientes que morreram (cenário 02):
0.1111111111111111

## Sexo dos pacientes

In [27]:
print('Sexo dos pacientes (cenário 01):')
print(scenario01['GENDER'].value_counts())
print(scenario01['GENDER'].value_counts(normalize = True))

print('\nSexo dos pacientes (cenário 02):')
print(scenario02['GENDER'].value_counts())
print(scenario02['GENDER'].value_counts(normalize = True))

Sexo dos pacientes (cenário 01):
M    70
F    69
Name: GENDER, dtype: int64
M    0.503597
F    0.496403
Name: GENDER, dtype: float64

Sexo dos pacientes (cenário 02):
F    66
M    51
Name: GENDER, dtype: int64
F    0.564103
M    0.435897
Name: GENDER, dtype: float64

In [28]:
print('Sexo dos pacientes que morreram (cenário 01):')
print(scenario01.loc[scenario01['DEATH_FN'] == 1,'GENDER'].value_counts())
print(scenario01.loc[scenario01['DEATH_FN'] == 1,'GENDER'].value_counts(normalize = True))

print('\nSexo dos pacientes que não morreram (cenário 01):')
print(scenario01.loc[scenario01['DEATH_FN'] == 0,'GENDER'].value_counts())
print(scenario01.loc[scenario01['DEATH_FN'] == 0,'GENDER'].value_counts(normalize = True))

print('\nSexo dos pacientes que morreram (cenário 02):')
print(scenario02.loc[scenario02['DEATH_FN'] == 1,'GENDER'].value_counts())
print(scenario02.loc[scenario02['DEATH_FN'] == 1,'GENDER'].value_counts(normalize = True))

print('\nSexo dos pacientes que não morreram (cenário 02):')
print(scenario02.loc[scenario02['DEATH_FN'] == 0,'GENDER'].value_counts())
print(scenario02.loc[scenario02['DEATH_FN'] == 0,'GENDER'].value_counts(normalize = True))

Sexo dos pacientes que morreram (cenário 01):
M    14
F    12
Name: GENDER, dtype: int64
M    0.538462
F    0.461538
Name: GENDER, dtype: float64

Sexo dos pacientes que não morreram (cenário 01):
F    57
M    56
Name: GENDER, dtype: int64
F    0.504425
M    0.495575
Name: GENDER, dtype: float64

Sexo dos pacientes que morreram (cenário 02):
F    7
M    6
Name: GENDER, dtype: int64
F    0.538462
M    0.461538
Name: GENDER, dtype: float64

Sexo dos pacientes que não morreram (cenário 02):
F    59
M    45
Name: GENDER, dtype: int64
F    0.567308
M    0.432692
Name: GENDER, dtype: float64

In [29]:
print('Porcentagem de mulheres que morreram (cenário 01):')
print(scenario01.loc[scenario01['DEATH_FN'] == 1,'GENDER'].value_counts()[1]/scenario01['GENDER'].value_counts()[1])
print('\nPorcentagem de homens que morreram (cenário 01):')
print(scenario01.loc[scenario01['DEATH_FN'] == 1,'GENDER'].value_counts()[0]/scenario01['GENDER'].value_counts()[0])
print('\nPorcentagem de mulheres que morreram (cenário 02):')
print(scenario02.loc[scenario02['DEATH_FN'] == 1,'GENDER'].value_counts()[0]/scenario02['GENDER'].value_counts()[0])
print('\nPorcentagem de homens que morreram (cenário 02):')
print(scenario02.loc[scenario02['DEATH_FN'] == 1,'GENDER'].value_counts()[1]/scenario02['GENDER'].value_counts()[1])

Porcentagem de mulheres que morreram (cenário 01):
0.17391304347826086

Porcentagem de homens que morreram (cenário 01):
0.2

Porcentagem de mulheres que morreram (cenário 02):
0.10606060606060606

Porcentagem de homens que morreram (cenário 02):
0.11764705882352941

## Etnia

In [30]:
print('Etnia dos pacientes (cenário 01):')
print(scenario01['ETHNICITY'].value_counts())
print(scenario01['ETHNICITY'].value_counts(normalize = True))

print('\nEtnia dos pacientes (cenário 02):')
print(scenario02['ETHNICITY'].value_counts())
print(scenario02['ETHNICITY'].value_counts(normalize = True))

Etnia dos pacientes (cenário 01):
nonhispanic    124
hispanic        15
Name: ETHNICITY, dtype: int64
nonhispanic    0.892086
hispanic       0.107914
Name: ETHNICITY, dtype: float64

Etnia dos pacientes (cenário 02):
nonhispanic    115
hispanic         2
Name: ETHNICITY, dtype: int64
nonhispanic    0.982906
hispanic       0.017094
Name: ETHNICITY, dtype: float64

In [31]:
print('Etnia dos pacientes que morreram (cenário 01):')
print(scenario01.loc[scenario01['DEATH_FN'] == 1,'ETHNICITY'].value_counts())
print(scenario01.loc[scenario01['DEATH_FN'] == 1,'ETHNICITY'].value_counts(normalize = True))

print('\nEtnia dos pacientes que não morreram (cenário 01):')
print(scenario01.loc[scenario01['DEATH_FN'] == 0,'ETHNICITY'].value_counts())
print(scenario01.loc[scenario01['DEATH_FN'] == 0,'ETHNICITY'].value_counts(normalize = True))

print('\nEtnia dos pacientes que morreram (cenário 02):')
print(scenario02.loc[scenario02['DEATH_FN'] == 1,'ETHNICITY'].value_counts())
print(scenario02.loc[scenario02['DEATH_FN'] == 1,'ETHNICITY'].value_counts(normalize = True))

print('\nEtnia dos pacientes que não morreram (cenário 02):')
print(scenario02.loc[scenario02['DEATH_FN'] == 0,'ETHNICITY'].value_counts())
print(scenario02.loc[scenario02['DEATH_FN'] == 0,'ETHNICITY'].value_counts(normalize = True))

Etnia dos pacientes que morreram (cenário 01):
nonhispanic    18
hispanic        8
Name: ETHNICITY, dtype: int64
nonhispanic    0.692308
hispanic       0.307692
Name: ETHNICITY, dtype: float64

Etnia dos pacientes que não morreram (cenário 01):
nonhispanic    106
hispanic         7
Name: ETHNICITY, dtype: int64
nonhispanic    0.938053
hispanic       0.061947
Name: ETHNICITY, dtype: float64

Etnia dos pacientes que morreram (cenário 02):
nonhispanic    13
Name: ETHNICITY, dtype: int64
nonhispanic    1.0
Name: ETHNICITY, dtype: float64

Etnia dos pacientes que não morreram (cenário 02):
nonhispanic    102
hispanic         2
Name: ETHNICITY, dtype: int64
nonhispanic    0.980769
hispanic       0.019231
Name: ETHNICITY, dtype: float64

In [32]:
print('Porcentagem de hispânicos que morreram (cenário 01):')
print(scenario01.loc[scenario01['DEATH_FN'] == 1,'ETHNICITY'].value_counts()[1]/scenario01['ETHNICITY'].value_counts()[1])
print('\nPorcentagem de não hispânicos que morreram (cenário 01):')
print(scenario01.loc[scenario01['DEATH_FN'] == 1,'ETHNICITY'].value_counts()[0]/scenario01['ETHNICITY'].value_counts()[0])

Porcentagem de hispânicos que morreram (cenário 01):
0.5333333333333333

Porcentagem de não hispânicos que morreram (cenário 01):
0.14516129032258066

## Raça

In [33]:
print('Raça dos pacientes (cenário 01):')
print(scenario01['RACE'].value_counts())
print(scenario01['RACE'].value_counts(normalize = True))

print('\nRaça dos pacientes (cenário 02):')
print(scenario02['RACE'].value_counts())
print(scenario02['RACE'].value_counts(normalize = True))

Raça dos pacientes (cenário 01):
white       113
black        13
asian         7
other         3
native        2
hawaiian      1
Name: RACE, dtype: int64
white       0.812950
black       0.093525
asian       0.050360
other       0.021583
native      0.014388
hawaiian    0.007194
Name: RACE, dtype: float64

Raça dos pacientes (cenário 02):
white       82
native      10
other        8
hawaiian     8
asian        7
black        2
Name: RACE, dtype: int64
white       0.700855
native      0.085470
other       0.068376
hawaiian    0.068376
asian       0.059829
black       0.017094
Name: RACE, dtype: float64

In [34]:
print('Raça dos pacientes que morreram (cenário 01):')
print(scenario01.loc[scenario01['DEATH_FN'] == 1,'RACE'].value_counts())
print(scenario01.loc[scenario01['DEATH_FN'] == 1,'RACE'].value_counts(normalize = True))

print('\nRaça dos pacientes que não morreram (cenário 01):')
print(scenario01.loc[scenario01['DEATH_FN'] == 0,'RACE'].value_counts())
print(scenario01.loc[scenario01['DEATH_FN'] == 0,'RACE'].value_counts(normalize = True))

print('\nRaça dos pacientes que morreram (cenário 02):')
print(scenario02.loc[scenario02['DEATH_FN'] == 1,'RACE'].value_counts())
print(scenario02.loc[scenario02['DEATH_FN'] == 1,'RACE'].value_counts(normalize = True))

print('\nRaça dos pacientes que não morreram (cenário 02):')
print(scenario02.loc[scenario02['DEATH_FN'] == 0,'RACE'].value_counts())
print(scenario02.loc[scenario02['DEATH_FN'] == 0,'RACE'].value_counts(normalize = True))

Raça dos pacientes que morreram (cenário 01):
white    24
other     1
black     1
Name: RACE, dtype: int64
white    0.923077
other    0.038462
black    0.038462
Name: RACE, dtype: float64

Raça dos pacientes que não morreram (cenário 01):
white       89
black       12
asian        7
native       2
other        2
hawaiian     1
Name: RACE, dtype: int64
white       0.787611
black       0.106195
asian       0.061947
native      0.017699
other       0.017699
hawaiian    0.008850
Name: RACE, dtype: float64

Raça dos pacientes que morreram (cenário 02):
white       11
hawaiian     1
native       1
Name: RACE, dtype: int64
white       0.846154
hawaiian    0.076923
native      0.076923
Name: RACE, dtype: float64

Raça dos pacientes que não morreram (cenário 02):
white       71
native       9
other        8
hawaiian     7
asian        7
black        2
Name: RACE, dtype: int64
white       0.682692
native      0.086538
other       0.076923
hawaiian    0.067308
asian       0.067308
black       0.019231
Name: RACE, dtype: float64

## Medicamento

In [35]:
print('Cenário 01:')
print(scenario01['MED_AMLD'].value_counts())
print(scenario01['MED_AMLD'].value_counts(normalize = True))
print('Cenário 02:')
print(scenario02['MED_AMLD'].value_counts())
print(scenario02['MED_AMLD'].value_counts(normalize = True))

Cenário 01:
0    102
1     37
Name: MED_AMLD, dtype: int64
0    0.733813
1    0.266187
Name: MED_AMLD, dtype: float64
Cenário 02:
0    88
1    29
Name: MED_AMLD, dtype: int64
0    0.752137
1    0.247863
Name: MED_AMLD, dtype: float64

In [36]:
print('Porcentagem dos que tomaram medicamento e morreram (cenário 01):')
print(scenario01.loc[scenario01['MED_AMLD'] == 1, 'DEATH_FN'].value_counts()[1]/scenario01['MED_AMLD'].value_counts()[1])
print('\nPorcentagem dos que não tomaram medicamento e morreram (cenário 01):')
print(scenario01.loc[scenario01['MED_AMLD'] == 0, 'DEATH_FN'].value_counts()[1]/scenario01['MED_AMLD'].value_counts()[0])
print('\nPorcentagem dos que tomaram medicamento e morreram (cenário 02):')
print(scenario02.loc[scenario02['MED_AMLD'] == 1, 'DEATH_FN'].value_counts()[1]/scenario02['MED_AMLD'].value_counts()[1])
print('\nPorcentagem dos que não tomaram medicamento e morreram (cenário 02):')
print(scenario02.loc[scenario02['MED_AMLD'] == 0, 'DEATH_FN'].value_counts()[1]/scenario02['MED_AMLD'].value_counts()[0])

Porcentagem dos que tomaram medicamento e morreram (cenário 01):
0.10810810810810811

Porcentagem dos que não tomaram medicamento e morreram (cenário 01):
0.21568627450980393

Porcentagem dos que tomaram medicamento e morreram (cenário 02):
0.10344827586206896

Porcentagem dos que não tomaram medicamento e morreram (cenário 02):
0.11363636363636363

# Gerando as tabelas finais de *features*

In [37]:
#Descartando a coluna com a data de nascimento
scenario01 = scenario01.drop('BIRTHDATE', axis=1)
scenario02 = scenario02.drop('BIRTHDATE', axis=1)

display(scenario01)
display(scenario02)

,PATIENT,RACE,ETHNICITY,GENDER,DEATH_FN,AGE_FN_YEARS,BACTEREMIA,WELLNESS_CONT,AMBULATORY_SYMPTOM_CONT,MED_AMLD,NEUT_CONT,BODY_TEMP_F
0,4288f90b-4774-c329-3176-c1482e824c04,white,nonhispanic,M,0,2,0,1.0,0.0,0,255.1,101.2
1,f03f50be-20b1-3eae-2ed1-bb478bceb320,white,nonhispanic,M,0,16,1,6.0,1.0,1,491.4,102.2
2,11089781-c268-6838-642e-2c2c9edbb694,white,nonhispanic,F,0,9,0,12.0,2.0,0,258.9,102.0
3,d7b9725d-889f-d178-cf41-dbf8b373eda9,black,nonhispanic,F,0,6,0,7.0,1.0,0,360.7,102.9
4,ed2bb6aa-1f3c-b72b-46a6-54f05cac7da7,asian,nonhispanic,M,0,12,0,7.0,2.0,0,364.6,100.6
...,...,...,...,...,...,...,...,...,...,...,...,...
134,7d87bdff-2df1-8162-80e4-2e406304515d,white,nonhispanic,M,0,2,0,4.0,0.0,0,479.1,101.0
135,d5c0cc48-5f8a-4533-325c-25a9c3284185,other,nonhispanic,F,0,3,1,11.0,1.0,1,476.6,101.6
136,a4cabcbc-8282-5599-6b69-01e28e69c045,black,nonhispanic,M,0,16,0,8.0,0.0,0,364.4,101.5
137,eca28495-500f-ab7e-356b-176f31382569,white,nonhispanic,F,0,3,0,11.0,0.0,0,425.7,100.8
138,c815ffa4-2917-2c09-1569-e90d5a89eeb2,white,nonhispanic,M,1,15,0,9.0,7.0,0,340.5,100.6

,PATIENT,RACE,ETHNICITY,GENDER,DEATH_FN,AGE_FN_YEARS,BACTEREMIA,WELLNESS_CONT,AMBULATORY_SYMPTOM_CONT,MED_AMLD,NEUT_CONT,BODY_TEMP_F
0,bb37561b-ba65-7c47-db5b-0641bca883b4,white,nonhispanic,M,0,3,0,9.0,1.0,0,406.5,102.3
1,678fc07c-1cb1-acc6-3553-d848200626e9,white,nonhispanic,F,0,16,0,9.0,2.0,0,265.8,101.9
2,04efa71e-b8ed-980b-94a1-cd25e94b6015,other,nonhispanic,F,0,4,0,13.0,2.0,0,496.3,101.7
3,1e466cbc-5018-4c1a-b132-cf8a4a4d87cf,white,nonhispanic,F,0,21,1,4.0,10.0,0,321.7,101.8
4,8e9d1dd0-085f-a629-3ea6-9033f330b383,white,nonhispanic,F,0,20,1,3.0,1.0,0,460.9,103.0
...,...,...,...,...,...,...,...,...,...,...,...,...
112,84c9e441-fa88-33c8-5d87-91b863998d26,white,nonhispanic,F,1,2,1,9.0,1.0,0,250.6,100.9
113,7837ca92-1dc3-b3ef-a7f9-4207e439775c,white,nonhispanic,M,0,17,0,15.0,2.0,0,435.9,101.1
114,3f3ad6c2-337b-9d48-47b7-b2197a0a0500,white,nonhispanic,F,1,2,1,9.0,0.0,1,448.6,100.8
115,32d8410a-cc4b-4d8b-601d-3ad2b8ef912b,white,nonhispanic,M,0,9,0,8.0,4.0,0,391.1,102.0
116,2e3402a9-45ff-3558-8450-375f17107ca0,white,nonhispanic,M,0,5,1,14.0,2.0,0,303.6,100.8

In [38]:
#Juntando as duas tabelas para gerar uma única tabela com os dois cenários
all = pd.concat([scenario01, scenario02], ignore_index=True)
display(all)

,PATIENT,RACE,ETHNICITY,GENDER,DEATH_FN,AGE_FN_YEARS,BACTEREMIA,WELLNESS_CONT,AMBULATORY_SYMPTOM_CONT,MED_AMLD,NEUT_CONT,BODY_TEMP_F
0,4288f90b-4774-c329-3176-c1482e824c04,white,nonhispanic,M,0,2,0,1.0,0.0,0,255.1,101.2
1,f03f50be-20b1-3eae-2ed1-bb478bceb320,white,nonhispanic,M,0,16,1,6.0,1.0,1,491.4,102.2
2,11089781-c268-6838-642e-2c2c9edbb694,white,nonhispanic,F,0,9,0,12.0,2.0,0,258.9,102.0
3,d7b9725d-889f-d178-cf41-dbf8b373eda9,black,nonhispanic,F,0,6,0,7.0,1.0,0,360.7,102.9
4,ed2bb6aa-1f3c-b72b-46a6-54f05cac7da7,asian,nonhispanic,M,0,12,0,7.0,2.0,0,364.6,100.6
...,...,...,...,...,...,...,...,...,...,...,...,...
251,84c9e441-fa88-33c8-5d87-91b863998d26,white,nonhispanic,F,1,2,1,9.0,1.0,0,250.6,100.9
252,7837ca92-1dc3-b3ef-a7f9-4207e439775c,white,nonhispanic,M,0,17,0,15.0,2.0,0,435.9,101.1
253,3f3ad6c2-337b-9d48-47b7-b2197a0a0500,white,nonhispanic,F,1,2,1,9.0,0.0,1,448.6,100.8
254,32d8410a-cc4b-4d8b-601d-3ad2b8ef912b,white,nonhispanic,M,0,9,0,8.0,4.0,0,391.1,102.0
255,2e3402a9-45ff-3558-8450-375f17107ca0,white,nonhispanic,M,0,5,1,14.0,2.0,0,303.6,100.8

In [39]:
#Salvando as tabelas como .csv
scenario01.to_csv('scenario01.csv', index = False)
scenario02.to_csv('scenario02.csv', index = False)
all.to_csv('all.csv', index = False)